
 export const movieData = [
    {  id: 1,
      title: 'Anbe Sivam', 
      poster: "https://i.pinimg.com/736x/db/3a/7b/db3a7b09573542a37d54ab101a776f67.jpg",
      hoverPoster:"https://fullyfilmy.in/cdn/shop/products/POS-148-NOFRAME.jpg?v=1677486840",
      releaseYear:"2003",
      duration:"2.58hr",
      languages:"3 languages",
      overview:"The film tells the story of Nallasivam and Anbarasu, two men of contrasting personalities who undertake an unexpected journey from Bhubaneswar to Chennai.'"},
      {  id: 2,
        title: 'Thuppakki', 
        poster: "https://image.tmdb.org/t/p/original/uTQNCqMnSDbZghFYNmzDvTVD413.jpg",
        hoverPoster:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLOz1rOE0hYMQvzvtpZZ1OSgoXr20pvXhebg&s",
        releaseYear:"2012",
        duration:"3hr",
        overview:"In a bomb blast, an army officer apprehends a sleeper agent who confesses that more bomb attacks are planned around the city;"},
        {  id: 3,
          title: 'Jailer', 
          poster: "https://upload.wikimedia.org/wikipedia/en/c/cb/Jailer_2023_Tamil_film_poster.jpg",
          hoverPoster:"https://i.pinimg.com/originals/7f/54/eb/7f54ebf507fc7984cba90ca8eaecd728.jpg",
          releaseYear:"2023",
          duration:"2.36hr",
          overview:"Muthuvel Pandian, a retired prison guard, sets out on a quest for revenge after his son goes missing while investigating a smuggling case."},
   {  id: 4,title: 'Movie 4', poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR96xJqMEeaycBmTOP1hPY3BKRRPWv6VqgtxA&s",hoverPoster:"https://www.acmodasi.in/amdb/images/movie/u/8/manjummel-boys-2024-dLesQf.jpg" },
    {  id: 5,title: 'Movie 5', poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQ_XP2eA6VfBNVpYWBRp4vvtp3jhGl7u8Pkw&s",hoverPoster:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRxgchXls68cYFxFxGoKsRG04e_sf5yyGHiYg&s" },
    {  id: 6,title: 'Movie 6', poster:"https://i.pinimg.com/736x/db/3a/7b/db3a7b09573542a37d54ab101a776f67.jpg",hoverPoster:"https://fullyfilmy.in/cdn/shop/products/POS-148-NOFRAME.jpg?v=1677486840" },
    {  id: 7,title: 'Movie 7', poster: "https://i.pinimg.com/736x/db/3a/7b/db3a7b09573542a37d54ab101a776f67.jpg",hoverPoster:"https://fullyfilmy.in/cdn/shop/products/POS-148-NOFRAME.jpg?v=1677486840" },
  ];

  export const seriesData = [
    {  id: 101,title: 'Movie 1', poster: "https://upload.wikimedia.org/wikipedia/en/2/26/Chutney_Sambar_Series.jpg"},
    {  id: 102,title: 'Movie 2', poster: "https://upload.wikimedia.org/wikipedia/en/2/26/Chutney_Sambar_Series.jpg" },
    {  id: 103,title: 'Movie 3', poster: "https://upload.wikimedia.org/wikipedia/en/2/26/Chutney_Sambar_Series.jpg"},
    {  id: 104,title: 'Movie 4', poster: "https://upload.wikimedia.org/wikipedia/en/2/26/Chutney_Sambar_Series.jpg" },
    {  id: 105,title: 'Movie 5', poster: "https://upload.wikimedia.org/wikipedia/en/2/26/Chutney_Sambar_Series.jpg" },
    {  id: 106,title: 'Movie 6', poster:"https://upload.wikimedia.org/wikipedia/en/2/26/Chutney_Sambar_Series.jpg" },
    {  id: 107,title: 'Movie 7', poster: "https://upload.wikimedia.org/wikipedia/en/2/26/Chutney_Sambar_Series.jpg" },
  ];